export enum NetworksList {
  ALGO = "ALGO",
  BTC = "BTC",
  BCH = "BCH",
  BSC = "BSC",
  BNB = "BNB",
  CELO = "CELO",
  DOGE = "DOGE",
  EGLD = "EGLD",
  ETH = "ETH",
  FLOW = "FLOW",
  ONE = "ONE",
  KLAY = "KLAY",
  KCS = "KCS",
  LTC = "LTC",
  MATIC = "MATIC",
  SOL = "SOL",
  XLM = "XLM",
  TRON = "TRON",
  VET = "VET",
  XDC = "XDC",
  XRP = "XRP",
}
